"""empty message

Revision ID: 96853b7a2097
Revises: 27e31ed98b7f
Create Date: 2024-07-27 20:33:29.995667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96853b7a2097'
down_revision = '27e31ed98b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
